calliostro_discogs:
  user_agent: 'CalliostroDiscogsBundle/2.0 +https://github.com/calliostro/discogs-bundle'
  consumer_key: '%env(DISCOGS_CONSUMER_KEY)%'
  consumer_secret: '%env(DISCOGS_CONSUMER_SECRET)%'
  throttle:
    # If activated, a new attempt is made later when the rate limit is reached
    enabled: true
    # Number of milliseconds to wait until the next attempt when the rate limit is reached
    microseconds: 1000000
  oauth:
    # If enabled, full OAuth 1.0a with access token/secret is used
    enabled: false
    # You can create a service implementing OAuthTokenProviderInterface (HWIOAuthBundle is supported by default)
    token_provider: calliostro_discogs.hwi_oauth_token_provider
